# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515171e0a33d1d2f8113d6f693e3a573bc1400495ed2c2b93852eb13c12eeb4f78d22b3ae8e467d0be619ee5e3bbb3b11e23e57f58ca820ed0f0f4cd6476c473

test:
  secret_key_base: 6c93f0e316865199626c74c61bbe33f303589d8a2c5d89d5d46ff328c2321c3e49d3e08e27a07a11a50a7bbaec2f7658673ca943d7980bebac6b18afdb4db30c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
